name: Deployment Success Metrics
on:
  workflow_dispatch:
jobs:
  ctoai-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 'Report Deployment Succeeded'
        uses: cto-ai/action@480fa119cca2295840029c32e2d958fb62f49d42
        id: ctoai-action
        with:
          team_id: ${{ secrets.CTOAI_TEAM }}
          token: ${{ secrets.CTOAI_TOKEN }}
          event_name: "deployment"
          event_action: "success"