name: Github Job Deployment Fail Metrics
on:
  workflow_dispatch:
jobs:
  ctoai-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 'Report Deployment Failed'
        run: |
          echo "Failed Deployment"
          exit 1